set -g terminal-features "tmux-256color:RGB"
set -g set-clipboard on

set -g base-index 1
set -g pane-base-index 1

set -g renumber-windows on
set -g mode-keys vi
set -g escape-time 0

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
unbind -T copy-mode-vi MouseDragEnd1Pane

set -g status-style "bg=default"
set -g window-status-current-style "bg=default fg=black,bright bold"
set -g status-justify absolute-centre
set -g status-position top
set -g status-left ""
set -g status-right "#[fg=black,bright]#S "

set -g message-style "fg=black,bright bold bg=default "
set -g mode-style "fg=black bg=blue"

set -g window-status-format "#I"
set -g window-status-current-format "#I"
set -g window-status-current-style "#{?window_zoomed_flag,fg=yellow,fg=magenta\#,nobold}"
set -g window-status-bell-style "fg=red,nobold"

set -g pane-border-lines simple
set -g pane-border-style fg=black,bright
set -g pane-active-border-style fg=magenta

unbind C-b
set -g prefix `
bind ` send-prefix

unbind %
unbind '"'

bind h split-window -h
bind | split-window -h

bind v split-window -v
bind - split-window -v

bind E show-environment -g

unbind r
bind r source-file "~/.config/tmux/tmux.conf"

set -g destroy-unattached off
bind-key x kill-pane

bind -n M-H previous-window
bind -n M-L next-window

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

unbind n
bind n display-popup -E 'sh -c "read -p \"Session name: \" name; tmux new-session -d -s \$name && tmux switch-client -t \$name"'

unbind t
bind t display-popup -d "#{pane_current_path}" -E "mksh"
