# ~/.config/fnott/fnott.ini

title-font=IosevkaTerm Nerd Font:size=11
summary-font=IosevkaTerm Nerd Font:size=11
body-font=IosevkaTerm Nerd Font:size=11

anchor=top-right
layer=overlay
max-width=360
max-height=120
edge-margin-vertical=10
edge-margin-horizontal=10
notification-margin=8
padding-vertical=12
padding-horizontal=12
border-size=2
border-radius=6

background=fbf1c7ff
title-color=282828ff
summary-color=282828ff
body-color=282828ff
border-color=458588ff
progress-color=458588ff
progress-style=bar

max-icon-size=32
default-timeout=5
selection-helper=mew

title-format=
summary-format=<b>%s</b>\n
body-format=%b

[low]
border-color=d5c4a1ff
title-color=282828ff
summary-color=282828ff
body-color=282828ff
default-timeout=3

[normal]
border-color=458588ff

[critical]
background=fbf1c7ff
title-color=9d0006ff
summary-color=282828ff
body-color=282828ff
border-color=cc241dff
default-timeout=0
