# ~/.config/fnott/fnott.ini

title-font=IosevkaTerm Nerd Font:size=11
summary-font=IosevkaTerm Nerd Font:size=11
body-font=IosevkaTerm Nerd Font:size=11

anchor=top-right
layer=overlay
max-width=360
max-height=120
edge-margin-vertical=10
edge-margin-horizontal=10
notification-margin=8
padding-vertical=12
padding-horizontal=12
border-size=2
border-radius=6

background=282828ff
title-color=ebdbb2ff
summary-color=ebdbb2ff
body-color=ebdbb2ff
border-color=83a598ff
progress-color=83a598ff
progress-style=bar

max-icon-size=32
default-timeout=5
selection-helper=mew

title-format=
summary-format=<b>%s</b>\n
body-format=%b

[low]
border-color=665c54ff
title-color=ebdbb2ff
summary-color=ebdbb2ff
body-color=ebdbb2ff
default-timeout=3

[normal]
border-color=83a598ff

[critical]
background=282828ff
title-color=fbf1c7ff
summary-color=fbf1c7ff
body-color=fbf1c7ff
border-color=fb4934ff
default-timeout=0
