evaluate-commands %sh{
    plugins="$kak_config/plugins"
    mkdir -p "$plugins"
    [ ! -e "$plugins/plug.kak" ] && \
        git clone -q https://github.com/andreyorst/plug.kak.git "$plugins/plug.kak"
    printf "%s\n" "source '$plugins/plug.kak/rc/plug.kak'"
}
plug "andreyorst/plug.kak" noload

plug "lePerdu/kakboard" %{
    hook global WinCreate .* %{ kakboard-enable }
}

set-option global tabstop 2
set-option global indentwidth 2

add-highlighter global/ number-lines -hlcursor -relative -separator "  " -cursor-separator " |"
add-highlighter global/ show-matching
set-option -add global ui_options terminal_assistant=none

declare-user-mode z-mode

map global z-mode <s-z> ': write-quit<ret>' -docstring 'write and quit (ZZ)'

map global z-mode <s-q> ': quit!<ret>' -docstring 'quit without saving (ZQ)'

map global normal <s-z> ': enter-user-mode z-mode<ret>'
