source "%val{config}/bundle/kak-bundle/rc/kak-bundle.kak"
bundle-noload kak-bundle https://codeberg.org/jdugan6240/kak-bundle
bundle kakboard https://github.com/lePerdu/kakboard.git %{
  hook global WinCreate .* %{ kakboard-enable }
}
bundle kakoune-snippets https://github.com/occivink/kakoune-snippets
bundle luar https://github.com/gustavo-hms/luar %{
  require-module luar
}

bundle peneira https://github.com/gustavo-hms/peneira %{
  require-module peneira
}

bundle auto-pairs https://github.com/alexherbo2/auto-pairs.kak %{
  hook global WinCreate .* %{ enable-auto-pairs }
}
bundle yummy https://github.com/Hjagu09/yummy.kak %{
  require-module yummy_devs_config
	yummy-enable
}
bundle kakoune-phantom-selection https://github.com/occivink/kakoune-phantom-selection

set-option global luar_interpreter luajit

eval %sh{kak-lsp}
lsp-enable


map global user l ':enter-user-mode lsp<ret>' -docstring 'LSP mode'

map global goto d <esc>:lsp-definition<ret> -docstring 'LSP definition'
map global goto r <esc>:lsp-references<ret> -docstring 'LSP references'
map global goto y <esc>:lsp-type-definition<ret> -docstring 'LSP type definition'

map global insert <tab> '<a-;>:try lsp-snippets-select-next-placeholders catch %{ execute-keys -with-hooks <lt>tab> }<ret>' -docstring 'Select next snippet placeholder'

map global object a '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
map global object <a-a> '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
map global object f '<a-semicolon>lsp-object Function Method<ret>' -docstring 'LSP function or method'
map global object t '<a-semicolon>lsp-object Class Interface Module Namespace Struct<ret>' -docstring 'LSP class or module'
map global object d '<a-semicolon>lsp-diagnostic-object error warning<ret>' -docstring 'LSP errors and warnings'
map global object D '<a-semicolon>lsp-diagnostic-object error<ret>' -docstring 'LSP errors'

hook global WinSetOption filetype=c %{
    set-option buffer lsp_servers %{
        [clangd]
        root_globs = ["compile_commands.json", ".clangd", ".git"]
        args = ["--background-index", "--clang-tidy"]
    }

    lsp-inlay-diagnostics-enable buffer
}
colorscheme gruv
set-option global tabstop 2
set-option global indentwidth 2
set-option global scrolloff 1,3
set-option global ui_options ncurses_status_on_top=true
set-option -add global ui_options terminal_assistant=none
add-highlighter global/ regex \h+$ 0:Error
add-highlighter global/ show-matching
add-highlighter global/indent show-whitespaces -tab "│" -indent "│" -spc " " -lf " "
add-highlighter global/ wrap -word -indent -marker '↩'

hook global WinCreate .* %{
    add-highlighter window/number-lines number-lines -hlcursor -relative -separator "  " -cursor-separator " |"
}

hook global InsertCompletionShow .* %{
    map window insert <tab> <c-n>
    map window insert <s-tab> <c-p>
}
hook global InsertCompletionHide .* %{
    unmap window insert <tab>
    unmap window insert <s-tab>
}
map global normal <c-p> ': peneira-files<ret>' -docstring 'Find files (peneira)'

declare-user-mode z-mode
map global z-mode <s-z> ': write-quit<ret>' -docstring 'write and quit (ZZ)'
map global z-mode <s-q> ': quit!<ret>' -docstring 'quit without saving (ZQ)'
map global normal <s-z> ': enter-user-mode z-mode<ret>'
#declare-option -hidden str modeline_git_branch
#hook global WinDisplay .* %{
  #set-option window modeline_git_branch %sh{
    #branch=$(git -C "${kak_buffile%/*}" rev-parse --abbrev-ref HEAD 2>/dev/null)
    #if [ -n "$branch" ]; then
      #printf "$branch "
    #fi
  #}
#}
#hook global NormalIdle .* %{
    #set-option global modelinefmt "{string}%opt{modeline_git_branch}  {type}{{context_info}} {{mode_info}} → %val{bufname}   {meta}%val{cursor_line}:%val{cursor_char_column}   %opt{lsp_modeline}"
#}


map global normal f     ": phantom-selection-add-selection<ret>"
map global normal F     ": phantom-selection-select-all; phantom-selection-clear<ret>"
map global normal <a-f> ": phantom-selection-iterate-next<ret>"
map global normal <a-F> ": phantom-selection-iterate-prev<ret>"

    # this would be nice, but currrently doesn't work
# see https://github.com/mawww/kakoune/issues/1916
#map global insert <a-f> "<a-;>: phantom-selection-iterate-next<ret>"
#map global insert <a-F> "<a-;>: phantom-selection-iterate-prev<ret>"
# so instead, have an approximate version that uses 'i'
map global insert <a-f> "<esc>: phantom-selection-iterate-next<ret>i"
map global insert <a-F> "<esc>: phantom-selection-iterate-prev<ret>i"
