#!/bin/sh

dbus-update-activation-environment --systemd --all

[ -f "$HOME/Wallpapers/cabin.png" ] && wbg "$HOME/Wallpapers/cabin.png" &

wlr-randr --output DP-1 --mode 1920x1080@100Hz &
foot --server &
fnott &

wayidle -t 300 zrwm-msg spawn 'waylock -init-color 0xfbf1c7 -input-color 0x458588 -fail-color 0xcc241d' &
wayidle -t 600 wlopm --off DP-1 resume wlopm --on DP-1 &

openrc --user gui &

slstatus -s | dwlb -status-stdin all &
exec zrwm | dwlb

